/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivePlanRouteImport } from './routes/active-plan'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AiTranslatorRouteImport } from './routes/ai-translator'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ClinicianRouteImport } from './routes/clinician'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivePlanRoute = ActivePlanRouteImport.update({
  id: '/active-plan',
  path: '/active-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTranslatorRoute = AiTranslatorRouteImport.update({
  id: '/ai-translator',
  path: '/ai-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianRoute = ClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-plan': typeof ActivePlanRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-translator': typeof AiTranslatorRoute
  '/capture': typeof CaptureRoute
  '/clinician': typeof ClinicianRoute
  '/messages': typeof MessagesRoute
  '/questionnaire': typeof QuestionnaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-plan': typeof ActivePlanRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-translator': typeof AiTranslatorRoute
  '/capture': typeof CaptureRoute
  '/clinician': typeof ClinicianRoute
  '/messages': typeof MessagesRoute
  '/questionnaire': typeof QuestionnaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-plan': typeof ActivePlanRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-translator': typeof AiTranslatorRoute
  '/capture': typeof CaptureRoute
  '/clinician': typeof ClinicianRoute
  '/messages': typeof MessagesRoute
  '/questionnaire': typeof QuestionnaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-plan'
    | '/admin'
    | '/ai-assistant'
    | '/ai-translator'
    | '/capture'
    | '/clinician'
    | '/messages'
    | '/questionnaire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-plan'
    | '/admin'
    | '/ai-assistant'
    | '/ai-translator'
    | '/capture'
    | '/clinician'
    | '/messages'
    | '/questionnaire'
  id:
    | '__root__'
    | '/'
    | '/active-plan'
    | '/admin'
    | '/ai-assistant'
    | '/ai-translator'
    | '/capture'
    | '/clinician'
    | '/messages'
    | '/questionnaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivePlanRoute: typeof ActivePlanRoute
  AdminRoute: typeof AdminRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AiTranslatorRoute: typeof AiTranslatorRoute
  CaptureRoute: typeof CaptureRoute
  ClinicianRoute: typeof ClinicianRoute
  MessagesRoute: typeof MessagesRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-plan': {
      id: '/active-plan'
      path: '/active-plan'
      fullPath: '/active-plan'
      preLoaderRoute: typeof ActivePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-translator': {
      id: '/ai-translator'
      path: '/ai-translator'
      fullPath: '/ai-translator'
      preLoaderRoute: typeof AiTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician': {
      id: '/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof ClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivePlanRoute: ActivePlanRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  AiTranslatorRoute: AiTranslatorRoute,
  CaptureRoute: CaptureRoute,
  ClinicianRoute: ClinicianRoute,
  MessagesRoute: MessagesRoute,
  QuestionnaireRoute: QuestionnaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
